/***************************************************************************
    importsub.h
                             -------------------
    Class Import::Srt
                             
    begin                : March 2015
    copyright            : (c) 2015 by Iven Wold - 526f6c616e642053756368616e

    license              : GPL v 2.0
    
   This class handles the import filter for sub (subtitle) files as
   generated by dv2sub ( http://dv2sub.sf.net )
   
   {0}{23}2005-06-24|15:48:29
   {24}{53}2005-06-24|15:48:30
   {54}{83}2005-06-24|15:48:31
   {84}{113}2005-06-24|15:48:32
    
****************************************************************************/

#ifndef __IMPORT_SUB_H__
#define __IMPORT_SUB_H__

#include "sourcefileentry.h"
//Added by qt3to4:
//#include <Q3ValueList>	//oxx

namespace Import
{

class Sub
{
public:

public:
   Sub ( );
  ~Sub ( );

  bool    import    ( float );
  bool    readFile  ( QString &, float );
  
  QList<Subtitles::entry *> m_listOfEntries;	//oxx
private:
  QString formatTimestamp   ( QString & );
  long    getTimeFromString ( QString & );

  float m_fFPS;
};

}

#endif // __IMPORT_SUB_H__
