######################################################################
# Automatically generated by qmake (2.01a) So. Mär 15 14:32:53 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += qdvdauthor.h
SOURCES += main.cpp qdvdauthor.cpp
